CREATE TABLE URL (
    `ID` bigint(16)  unsigned NOT NULL AUTO_INCREMENT,
    `CLIENT_ID` VARCHAR(36) NOT NULL UNIQUE,
    `LONG_URL` VARCHAR(2048) NOT NULL,
    `SHORT_URL` VARCHAR(256) NOT NULL,
    `CREATE_DATETIME` DATETIME(3) NOT NULL,
    PRIMARY KEY(`ID`),
    UNIQUE KEY `URL_PK`(`ID`),
    UNIQUE KEY `URL_PK_MUL01`(`CLIENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1;